export const SET_LOADING = 'SET_LOADING';
export const GET_MOVIES = 'GET_MOVIES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const GET_MOVIEDETAILS = 'GET_MOVIEDETAILES';
export const GET_MOVIECASTS = 'GET_MOVIECASTS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
